iris %>% glimpse()
dplyr.tidyverse.org
iris2 <- iris %>% filter(Species=="Setosa")
filter(iris, Species=="Setosa")
iris2 %>% dim()
iris3 <- iris %>% filter (Sepal.Length >2)
iis3 %>% dim()
iris3 %>% dim()
iris3 <- iris %>% filter (Sepal.Length >3)
iris3 %>% dim()
iris3 <- iris %>% filter (Sepal.Length >3)
iris3 %>% dim()
iris3 %>% dim()iris3 <- iris %>% filter (Sepal.Length >5)
iris3 %>% dim()
iris3 <- iris %>% filter (Sepal.Length >5.2)
iris3 %>% dim()
iris3 <- iris %>% filter (Sepal.Length >5.4)
iris3 %>% dim()
iris3 <- iris %>% filter (Sepal.Length >5.6)
iris3 %>% dim()
iris %>% filter(Sepal.Lgth>5) %>% dim()
iris %>% filter(Sepal.Length>5) %>% dim()
history (60)
